{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
  labels:
    release: "{{ .Release.Name }}"
    app: "{{ .Release.Name }}"
    {{- range $key, $value := .Values.specs.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
rules:
{{ toYaml .Values.rbac.rules | indent 2 }}
{{- end }}
