{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  {{- if eq .Values.secret.enabled true }}
  {{- if eq .Values.secretVolume.enabled true }}
  name: {{ .Release.Name }}-config-secret
  {{- else if eq .Values.secret.enabled true }}
  name: {{ .Release.Name }}-secret
  {{- else }}
  name: {{ .Release.Name }}-default-secret
  {{- end }}
  {{- end }}

  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.content }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
