{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    {{- range $key, $value := .Values.specs.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
#   {{- if and .Values.service.annotationsEnabled .Values.specs.annotations }}
#   annotations:
#     {{- range $key, $value := .Values.specs.annotations }}
#     {{ $key }}: {{ $value | quote }}
#     {{- end }}
#   {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
{{- end }}
